version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install boto3 scikit-learn pandas joblib jupyter nbconvert

  pre_build:
    commands:
      - echo "Starting training pipeline..."

  build:
  commands:
    - jupyter kernelspec list  # shows available kernels
    - jupyter nbconvert --to notebook --execute train/train_validate.ipynb 
      --output train/train_validate_output.ipynb
      --ExecutePreprocessor.kernel_name=python3

  post_build:
    commands:
      - echo "Training complete!"